### ISSUE TITLE
RustCrypto crates as an experimental impl for thrussh

### ISSUE THREAD

**Issue by darleybarreto** [RustCrypto/AEADs#330] opened 2021-06-28 14:05 UTC
Hi folks, 

First of all, amazing work! Second, I am not sure if here is the right place to ask, since this is more a discussion than an issue. So forgive me if here is not the proper place.

A bit of context: [thrussh](https://docs.rs/thrussh/) is an implementation of the SSH 2 protocol, both server-side and client-side. It uses `libsodium` to provide chacha20, poly1305, ed25519 and scalarmult_curve25519 functionalities. [Recently](https://nest.pijul.com/pijul/thrussh/discussions/24) I wondered if one could add an experimental feature gate to test an alternative impl using RustCrypto. 

What came up in the discussion was

1. Are the RNGs robust to current computations (so a malicious agent cannot take advantage of them)?
2. What you folks recommend to increase robustness, e.g.,  adding random timers around the crypto functions calls?

Finally, I would be thrilled to know your thoughts on this.

cc @P-E-Meunier

**Comment by tarcieri** [comment] 2021-06-28 14:39
> Are the RNGs robust to current computations (so a malicious agent cannot take advantage of them)?

Our crates do not provide or make assumptions about RNGs, but rather allow you to plug in any explicitly parameterized RNG you want using traits from the `rand_core` crate. They pretty much all use a signature of `impl CryptoRng + RngCore`.

> What you folks recommend to increase robustness, e.g., adding random timers around the crypto functions calls?

Our implementations of ciphers used in the context of a protocol like OpenSSH already take great care to avoid any use of things like lookup tables, secret-dependent pointers, or secret-dependent branches, often with state-of-the-art techniques (e.g. the `aes` crate uses a technique called fixslicing), and making use of the `subtle` crate for things like constant-time comparisons.

There's little we can recommend beyond that. A few of our crates do offer random blinding as an option, however that's as an off-by-default alternative to a constant-time algorithm for the purposes of embedded use and we do not recommend using such techniques except in unusual circumstances.

**Comment by P-E-Meunier** [comment] 2021-06-29 14:07
More generally (I agree RNGs aren't a major concern), do you foresee any problem with moving to RustCrypto instead of LibSodium + OpenSSL for an SSH client and server? Any reason you wouldn't make that move?

**Comment by tarcieri** [comment] 2021-06-30 01:35
I'm one of the earliest users and binding authors for libsodium. It's a great library.

The story around Rust bindings is a bit more complicated though. I've contributed to `sodiumoxide` in the past, but that project seems stalled. I don't know about successor projects.

I think there are a lot of nice benefits to pure Rust projects if possible, but will concede that our crates have not received the same degree of scrutiny.

**Comment by P-E-Meunier** [comment] 2021-06-30 06:18
Thrussh is currently using its own bindings, because we don't need the full thing, and want bindings as stable as possible (which wasn't the case of things like sodiumoxide, for some time at least).

Well, if the only difference is scrutiny, you won't get it used without having more eyes on it, which you won't get without getting it used. I know the feeling only too well… This is even a strong argument for me to use it, actually.

Once I figure out the subset of your functions I need, I can try reading the code at least for those (how stable are they?).

**Comment by tarcieri** [comment] 2021-07-01 16:11
FWIW, the `aes-gcm` and `chacha20poly1305` crates, and their relevant dependencies (e.g. the `aes`, `chacha20`, `ghash`/`polyval`, and `poly1305`) crates have been audited once by NCC Group. We've done a lot of work on them since though, so it's probably about time for another audit.

I'd say the crates are fairly stable: we do continue to make breaking changes, but for most users upgrades are drop-in. As const generics evolve we will be doing work to replace `generic-array` with them, but we still need more stable features to happen so that may not be until 2022.

**Comment by newpavlov** [comment] 2021-07-09 00:30
>Are the RNGs robust to current computations (so a malicious agent cannot take advantage of them)?

It should be enough to simply use [`OsRng`](https://docs.rs/rand_core/0.6.3/rand_core/struct.OsRng.html) or [`ThreadRng`](https://docs.rs/rand/0.8.4/rand/rngs/struct.ThreadRng.html). The former is a thin wrapper around OS randomness source (see the [`getrandom` docs](https://docs.rs/getrandom/) for details), while the latter uses user-space RNG (ChaCha12), which gets periodically re-seeded from `OsRng`. For your application I think `OsRng` should be a good fit. It usually slower than `ThreadRng`, but you will pull significantly less code (only `getrandom` + `rand_core`) and RNG stack will be significantly simpler (no thread local storage, re-seeding, and intermediate CSPRNG).

>What you folks recommend to increase robustness, e.g., adding random timers around the crypto functions calls?

ChaCha20 is constant time by design and our implementation of Poly1305 should be constant time (at least on x86-64). Ed25519 implementation from the [dalek cryptography](https://github.com/dalek-cryptography) group should be constant time as well.

BTW if you have any additional questions, we have [Zulip Chat](https://rustcrypto.zulipchat.com/)). It should be more convenient for such questions.

Since the OP questions are answered, I think we can close this issue?

**Comment by darleybarreto** [comment] 2021-07-09 17:10
Hey @newpavlov, thank you so much for the clarification. 

> BTW if you have any additional questions, we have Zulip Chat). It should be more convenient for such questions.

Asking on Zulip instead of opening an issue would have been the right place for this, my bad. Any future question I'll reach there for sure, thanks for pointing this!

**Comment by tarcieri** [comment] 2021-07-09 22:41
Gonna go ahead and close this, but feel free to reach out on Zulip with additional questions

**Closed by tarcieri** 2021-07-09 22:41 UTC
